////////////////////////////////////////////////////////
// This file was auto-generated by ruby_bindings.zig //
//              Do not manually modify.              //
////////////////////////////////////////////////////////

#ifndef RB_TB_GEN_H
#define RB_TB_GEN_H

#include "ruby.h"
#include "tb_client.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static inline void rb_tb_pack_u128(VALUE v, void *dst) {
    rb_integer_pack(v, dst, 16, 1, 0, INTEGER_PACK_LITTLE_ENDIAN);
}

static inline VALUE rb_tb_unpack_u128(const void *src) {
    return rb_integer_unpack(src, 16, 1, 0, INTEGER_PACK_LITTLE_ENDIAN);
}

static inline void tb_assert_fail(
    const char *condition,
    int line,
    const char *function
) {
    fprintf(stderr, "tb_assert failed: %s at line %d in %s\n", condition, line, function);
    abort();
}

// A version of `assert` macro that's always on regardless of NDEBUG macro.
#define tb_assert(condition) \
    do { \
        if (!(condition)) { \
            tb_assert_fail(#condition, __LINE__, __func__); \
        } \
    } while (0)
static const char *rb_tb_init_error_message(TB_INIT_STATUS status) {
    switch (status) {
    case TB_INIT_SUCCESS:
        return "success";
    case TB_INIT_UNEXPECTED:
        return "unexpected";
    case TB_INIT_OUT_OF_MEMORY:
        return "out_of_memory";
    case TB_INIT_ADDRESS_INVALID:
        return "address_invalid";
    case TB_INIT_ADDRESS_LIMIT_EXCEEDED:
        return "address_limit_exceeded";
    case TB_INIT_SYSTEM_RESOURCES:
        return "system_resources";
    case TB_INIT_NETWORK_SUBSYSTEM:
        return "network_subsystem";
    default:
        return "unknown";
    }
}

static VALUE rb_tb_deserialize_lookup_accounts(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::Account");
    tb_assert(buf_size % sizeof(tb_account_t) == 0);
    long count = (long)(buf_size / sizeof(tb_account_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_account_t *items = (const tb_account_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_account_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@id"), rb_tb_unpack_u128(&item->id));
        rb_ivar_set(obj, rb_intern("@debits_pending"), rb_tb_unpack_u128(&item->debits_pending));
        rb_ivar_set(obj, rb_intern("@debits_posted"), rb_tb_unpack_u128(&item->debits_posted));
        rb_ivar_set(obj, rb_intern("@credits_pending"), rb_tb_unpack_u128(&item->credits_pending));
        rb_ivar_set(obj, rb_intern("@credits_posted"), rb_tb_unpack_u128(&item->credits_posted));
        rb_ivar_set(obj, rb_intern("@user_data_128"), rb_tb_unpack_u128(&item->user_data_128));
        rb_ivar_set(obj, rb_intern("@user_data_64"), ULL2NUM(item->user_data_64));
        rb_ivar_set(obj, rb_intern("@user_data_32"), UINT2NUM(item->user_data_32));
        tb_assert(item->reserved == 0);
        rb_ivar_set(obj, rb_intern("@ledger"), UINT2NUM(item->ledger));
        rb_ivar_set(obj, rb_intern("@code"), UINT2NUM(item->code));
        rb_ivar_set(obj, rb_intern("@flags"), UINT2NUM(item->flags));
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ary_push(results, obj);
    }
    return results;
}

static VALUE rb_tb_deserialize_lookup_transfers(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::Transfer");
    tb_assert(buf_size % sizeof(tb_transfer_t) == 0);
    long count = (long)(buf_size / sizeof(tb_transfer_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_transfer_t *items = (const tb_transfer_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_transfer_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@id"), rb_tb_unpack_u128(&item->id));
        rb_ivar_set(obj, rb_intern("@debit_account_id"), rb_tb_unpack_u128(&item->debit_account_id));
        rb_ivar_set(obj, rb_intern("@credit_account_id"), rb_tb_unpack_u128(&item->credit_account_id));
        rb_ivar_set(obj, rb_intern("@amount"), rb_tb_unpack_u128(&item->amount));
        rb_ivar_set(obj, rb_intern("@pending_id"), rb_tb_unpack_u128(&item->pending_id));
        rb_ivar_set(obj, rb_intern("@user_data_128"), rb_tb_unpack_u128(&item->user_data_128));
        rb_ivar_set(obj, rb_intern("@user_data_64"), ULL2NUM(item->user_data_64));
        rb_ivar_set(obj, rb_intern("@user_data_32"), UINT2NUM(item->user_data_32));
        rb_ivar_set(obj, rb_intern("@timeout"), UINT2NUM(item->timeout));
        rb_ivar_set(obj, rb_intern("@ledger"), UINT2NUM(item->ledger));
        rb_ivar_set(obj, rb_intern("@code"), UINT2NUM(item->code));
        rb_ivar_set(obj, rb_intern("@flags"), UINT2NUM(item->flags));
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_get_account_transfers(VALUE items_rb, uint8_t *buf, long count) {
    tb_account_filter_t *items = (tb_account_filter_t *)buf;
    for (long i = 0; i < count; i++) {
        VALUE item_rb = RARRAY_AREF(items_rb, i);
        tb_account_filter_t *item = &items[i];
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@account_id")), &item->account_id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@user_data_128")), &item->user_data_128);
        item->user_data_64 = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@user_data_64")));
        item->user_data_32 = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@user_data_32")));
        item->code = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@code")));
        memset(item->reserved, 0, sizeof(item->reserved));
        item->timestamp_min = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_min")));
        item->timestamp_max = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_max")));
        item->limit = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@limit")));
        item->flags = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@flags")));
    }
}

static VALUE rb_tb_deserialize_get_account_transfers(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::Transfer");
    tb_assert(buf_size % sizeof(tb_transfer_t) == 0);
    long count = (long)(buf_size / sizeof(tb_transfer_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_transfer_t *items = (const tb_transfer_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_transfer_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@id"), rb_tb_unpack_u128(&item->id));
        rb_ivar_set(obj, rb_intern("@debit_account_id"), rb_tb_unpack_u128(&item->debit_account_id));
        rb_ivar_set(obj, rb_intern("@credit_account_id"), rb_tb_unpack_u128(&item->credit_account_id));
        rb_ivar_set(obj, rb_intern("@amount"), rb_tb_unpack_u128(&item->amount));
        rb_ivar_set(obj, rb_intern("@pending_id"), rb_tb_unpack_u128(&item->pending_id));
        rb_ivar_set(obj, rb_intern("@user_data_128"), rb_tb_unpack_u128(&item->user_data_128));
        rb_ivar_set(obj, rb_intern("@user_data_64"), ULL2NUM(item->user_data_64));
        rb_ivar_set(obj, rb_intern("@user_data_32"), UINT2NUM(item->user_data_32));
        rb_ivar_set(obj, rb_intern("@timeout"), UINT2NUM(item->timeout));
        rb_ivar_set(obj, rb_intern("@ledger"), UINT2NUM(item->ledger));
        rb_ivar_set(obj, rb_intern("@code"), UINT2NUM(item->code));
        rb_ivar_set(obj, rb_intern("@flags"), UINT2NUM(item->flags));
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_get_account_balances(VALUE items_rb, uint8_t *buf, long count) {
    tb_account_filter_t *items = (tb_account_filter_t *)buf;
    for (long i = 0; i < count; i++) {
        VALUE item_rb = RARRAY_AREF(items_rb, i);
        tb_account_filter_t *item = &items[i];
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@account_id")), &item->account_id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@user_data_128")), &item->user_data_128);
        item->user_data_64 = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@user_data_64")));
        item->user_data_32 = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@user_data_32")));
        item->code = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@code")));
        memset(item->reserved, 0, sizeof(item->reserved));
        item->timestamp_min = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_min")));
        item->timestamp_max = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_max")));
        item->limit = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@limit")));
        item->flags = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@flags")));
    }
}

static VALUE rb_tb_deserialize_get_account_balances(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::AccountBalance");
    tb_assert(buf_size % sizeof(tb_account_balance_t) == 0);
    long count = (long)(buf_size / sizeof(tb_account_balance_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_account_balance_t *items = (const tb_account_balance_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_account_balance_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@debits_pending"), rb_tb_unpack_u128(&item->debits_pending));
        rb_ivar_set(obj, rb_intern("@debits_posted"), rb_tb_unpack_u128(&item->debits_posted));
        rb_ivar_set(obj, rb_intern("@credits_pending"), rb_tb_unpack_u128(&item->credits_pending));
        rb_ivar_set(obj, rb_intern("@credits_posted"), rb_tb_unpack_u128(&item->credits_posted));
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        uint8_t zero[sizeof(item->reserved)] = {0};
        tb_assert(memcmp(item->reserved, zero, sizeof(item->reserved)) == 0);
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_query_accounts(VALUE items_rb, uint8_t *buf, long count) {
    tb_query_filter_t *items = (tb_query_filter_t *)buf;
    for (long i = 0; i < count; i++) {
        VALUE item_rb = RARRAY_AREF(items_rb, i);
        tb_query_filter_t *item = &items[i];
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@user_data_128")), &item->user_data_128);
        item->user_data_64 = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@user_data_64")));
        item->user_data_32 = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@user_data_32")));
        item->ledger = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@ledger")));
        item->code = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@code")));
        memset(item->reserved, 0, sizeof(item->reserved));
        item->timestamp_min = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_min")));
        item->timestamp_max = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_max")));
        item->limit = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@limit")));
        item->flags = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@flags")));
    }
}

static VALUE rb_tb_deserialize_query_accounts(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::Account");
    tb_assert(buf_size % sizeof(tb_account_t) == 0);
    long count = (long)(buf_size / sizeof(tb_account_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_account_t *items = (const tb_account_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_account_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@id"), rb_tb_unpack_u128(&item->id));
        rb_ivar_set(obj, rb_intern("@debits_pending"), rb_tb_unpack_u128(&item->debits_pending));
        rb_ivar_set(obj, rb_intern("@debits_posted"), rb_tb_unpack_u128(&item->debits_posted));
        rb_ivar_set(obj, rb_intern("@credits_pending"), rb_tb_unpack_u128(&item->credits_pending));
        rb_ivar_set(obj, rb_intern("@credits_posted"), rb_tb_unpack_u128(&item->credits_posted));
        rb_ivar_set(obj, rb_intern("@user_data_128"), rb_tb_unpack_u128(&item->user_data_128));
        rb_ivar_set(obj, rb_intern("@user_data_64"), ULL2NUM(item->user_data_64));
        rb_ivar_set(obj, rb_intern("@user_data_32"), UINT2NUM(item->user_data_32));
        tb_assert(item->reserved == 0);
        rb_ivar_set(obj, rb_intern("@ledger"), UINT2NUM(item->ledger));
        rb_ivar_set(obj, rb_intern("@code"), UINT2NUM(item->code));
        rb_ivar_set(obj, rb_intern("@flags"), UINT2NUM(item->flags));
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_query_transfers(VALUE items_rb, uint8_t *buf, long count) {
    tb_query_filter_t *items = (tb_query_filter_t *)buf;
    for (long i = 0; i < count; i++) {
        VALUE item_rb = RARRAY_AREF(items_rb, i);
        tb_query_filter_t *item = &items[i];
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@user_data_128")), &item->user_data_128);
        item->user_data_64 = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@user_data_64")));
        item->user_data_32 = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@user_data_32")));
        item->ledger = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@ledger")));
        item->code = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@code")));
        memset(item->reserved, 0, sizeof(item->reserved));
        item->timestamp_min = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_min")));
        item->timestamp_max = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp_max")));
        item->limit = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@limit")));
        item->flags = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@flags")));
    }
}

static VALUE rb_tb_deserialize_query_transfers(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::Transfer");
    tb_assert(buf_size % sizeof(tb_transfer_t) == 0);
    long count = (long)(buf_size / sizeof(tb_transfer_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_transfer_t *items = (const tb_transfer_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_transfer_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@id"), rb_tb_unpack_u128(&item->id));
        rb_ivar_set(obj, rb_intern("@debit_account_id"), rb_tb_unpack_u128(&item->debit_account_id));
        rb_ivar_set(obj, rb_intern("@credit_account_id"), rb_tb_unpack_u128(&item->credit_account_id));
        rb_ivar_set(obj, rb_intern("@amount"), rb_tb_unpack_u128(&item->amount));
        rb_ivar_set(obj, rb_intern("@pending_id"), rb_tb_unpack_u128(&item->pending_id));
        rb_ivar_set(obj, rb_intern("@user_data_128"), rb_tb_unpack_u128(&item->user_data_128));
        rb_ivar_set(obj, rb_intern("@user_data_64"), ULL2NUM(item->user_data_64));
        rb_ivar_set(obj, rb_intern("@user_data_32"), UINT2NUM(item->user_data_32));
        rb_ivar_set(obj, rb_intern("@timeout"), UINT2NUM(item->timeout));
        rb_ivar_set(obj, rb_intern("@ledger"), UINT2NUM(item->ledger));
        rb_ivar_set(obj, rb_intern("@code"), UINT2NUM(item->code));
        rb_ivar_set(obj, rb_intern("@flags"), UINT2NUM(item->flags));
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_create_accounts(VALUE items_rb, uint8_t *buf, long count) {
    tb_account_t *items = (tb_account_t *)buf;
    for (long i = 0; i < count; i++) {
        VALUE item_rb = RARRAY_AREF(items_rb, i);
        tb_account_t *item = &items[i];
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@id")), &item->id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@debits_pending")), &item->debits_pending);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@debits_posted")), &item->debits_posted);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@credits_pending")), &item->credits_pending);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@credits_posted")), &item->credits_posted);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@user_data_128")), &item->user_data_128);
        item->user_data_64 = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@user_data_64")));
        item->user_data_32 = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@user_data_32")));
        item->reserved = 0;
        item->ledger = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@ledger")));
        item->code = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@code")));
        item->flags = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@flags")));
        item->timestamp = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp")));
    }
}

static VALUE rb_tb_deserialize_create_accounts(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::CreateAccountResult");
    tb_assert(buf_size % sizeof(tb_create_account_result_t) == 0);
    long count = (long)(buf_size / sizeof(tb_create_account_result_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_create_account_result_t *items = (const tb_create_account_result_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_create_account_result_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ivar_set(obj, rb_intern("@status"), UINT2NUM(item->status));
        tb_assert(item->reserved == 0);
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_create_transfers(VALUE items_rb, uint8_t *buf, long count) {
    tb_transfer_t *items = (tb_transfer_t *)buf;
    for (long i = 0; i < count; i++) {
        VALUE item_rb = RARRAY_AREF(items_rb, i);
        tb_transfer_t *item = &items[i];
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@id")), &item->id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@debit_account_id")), &item->debit_account_id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@credit_account_id")), &item->credit_account_id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@amount")), &item->amount);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@pending_id")), &item->pending_id);
        rb_tb_pack_u128(rb_ivar_get(item_rb, rb_intern("@user_data_128")), &item->user_data_128);
        item->user_data_64 = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@user_data_64")));
        item->user_data_32 = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@user_data_32")));
        item->timeout = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@timeout")));
        item->ledger = (uint32_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@ledger")));
        item->code = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@code")));
        item->flags = (uint16_t)NUM2UINT(rb_ivar_get(item_rb, rb_intern("@flags")));
        item->timestamp = NUM2ULL(rb_ivar_get(item_rb, rb_intern("@timestamp")));
    }
}

static VALUE rb_tb_deserialize_create_transfers(const uint8_t *buf, uint32_t buf_size) {
    VALUE klass = rb_path2class("TigerBeetle::CreateTransferResult");
    tb_assert(buf_size % sizeof(tb_create_transfer_result_t) == 0);
    long count = (long)(buf_size / sizeof(tb_create_transfer_result_t));
    VALUE results = rb_ary_new_capa(count);
    const tb_create_transfer_result_t *items = (const tb_create_transfer_result_t *)buf;
    for (long i = 0; i < count; i++) {
        const tb_create_transfer_result_t *item = &items[i];
        VALUE obj = rb_obj_alloc(klass);
        rb_ivar_set(obj, rb_intern("@timestamp"), ULL2NUM(item->timestamp));
        rb_ivar_set(obj, rb_intern("@status"), UINT2NUM(item->status));
        tb_assert(item->reserved == 0);
        rb_ary_push(results, obj);
    }
    return results;
}

static void rb_tb_serialize_u128(VALUE items_rb, uint8_t *buf, long count) {
    tb_uint128_t *ids = (tb_uint128_t *)buf;
    for (long i = 0; i < count; i++) {
        rb_tb_pack_u128(RARRAY_AREF(items_rb, i), &ids[i]);
    }
}

static size_t rb_tb_event_size(TB_OPERATION operation) {
    switch (operation) {
    case TB_OPERATION_LOOKUP_ACCOUNTS:
        return sizeof(tb_uint128_t);
    case TB_OPERATION_LOOKUP_TRANSFERS:
        return sizeof(tb_uint128_t);
    case TB_OPERATION_GET_ACCOUNT_TRANSFERS:
        return sizeof(tb_account_filter_t);
    case TB_OPERATION_GET_ACCOUNT_BALANCES:
        return sizeof(tb_account_filter_t);
    case TB_OPERATION_QUERY_ACCOUNTS:
        return sizeof(tb_query_filter_t);
    case TB_OPERATION_QUERY_TRANSFERS:
        return sizeof(tb_query_filter_t);
    case TB_OPERATION_CREATE_ACCOUNTS:
        return sizeof(tb_account_t);
    case TB_OPERATION_CREATE_TRANSFERS:
        return sizeof(tb_transfer_t);
    default:
        rb_raise(rb_eRuntimeError, "unsupported operation: %d", (int)operation);
        return 0;
    }
}

static void rb_tb_serialize(
    TB_OPERATION operation,
    VALUE items_rb,
    uint8_t *buf,
    long count
) {
    switch (operation) {
    case TB_OPERATION_LOOKUP_ACCOUNTS:
        rb_tb_serialize_u128(items_rb, buf, count);
        break;
    case TB_OPERATION_LOOKUP_TRANSFERS:
        rb_tb_serialize_u128(items_rb, buf, count);
        break;
    case TB_OPERATION_GET_ACCOUNT_TRANSFERS:
        rb_tb_serialize_get_account_transfers(items_rb, buf, count);
        break;
    case TB_OPERATION_GET_ACCOUNT_BALANCES:
        rb_tb_serialize_get_account_balances(items_rb, buf, count);
        break;
    case TB_OPERATION_QUERY_ACCOUNTS:
        rb_tb_serialize_query_accounts(items_rb, buf, count);
        break;
    case TB_OPERATION_QUERY_TRANSFERS:
        rb_tb_serialize_query_transfers(items_rb, buf, count);
        break;
    case TB_OPERATION_CREATE_ACCOUNTS:
        rb_tb_serialize_create_accounts(items_rb, buf, count);
        break;
    case TB_OPERATION_CREATE_TRANSFERS:
        rb_tb_serialize_create_transfers(items_rb, buf, count);
        break;
    default:
        rb_raise(rb_eRuntimeError, "unsupported operation: %d", (int)operation);
    }
}

static VALUE rb_tb_deserialize(
    TB_OPERATION operation,
    const uint8_t *buf,
    uint32_t buf_size
) {
    switch (operation) {
    case TB_OPERATION_LOOKUP_ACCOUNTS:
        return rb_tb_deserialize_lookup_accounts(buf, buf_size);
    case TB_OPERATION_LOOKUP_TRANSFERS:
        return rb_tb_deserialize_lookup_transfers(buf, buf_size);
    case TB_OPERATION_GET_ACCOUNT_TRANSFERS:
        return rb_tb_deserialize_get_account_transfers(buf, buf_size);
    case TB_OPERATION_GET_ACCOUNT_BALANCES:
        return rb_tb_deserialize_get_account_balances(buf, buf_size);
    case TB_OPERATION_QUERY_ACCOUNTS:
        return rb_tb_deserialize_query_accounts(buf, buf_size);
    case TB_OPERATION_QUERY_TRANSFERS:
        return rb_tb_deserialize_query_transfers(buf, buf_size);
    case TB_OPERATION_CREATE_ACCOUNTS:
        return rb_tb_deserialize_create_accounts(buf, buf_size);
    case TB_OPERATION_CREATE_TRANSFERS:
        return rb_tb_deserialize_create_transfers(buf, buf_size);
    default:
        rb_raise(rb_eRuntimeError, "unsupported operation: %d", (int)operation);
    }
}
#endif
