#!/usr/bin/env bash
set -eu

mkdir -p ~/.ssh
echo -e "${TIGERBEETLE_GO_DEPLOY_KEY}" > ~/.ssh/id_ed25519
chmod 600 ~/.ssh/id_ed25519

git clone --no-checkout git@github.com:tigerbeetledb/tigerbeetle-go.git ~/tigerbeetle-go
cp -R . ~/tigerbeetle-go
cat << EOF > ~/tigerbeetle-go/README.md
# tigerbeetle-go
This repo has been automatically generated from [tigerbeetledb/tigerbeetle@${GITHUB_SHA}](https://github.com/tigerbeetledb/tigerbeetle/commit/${GITHUB_SHA}) to keep binary blobs out of the monorepo. Please see [https://github.com/tigerbeetledb/tigerbeetle/tree/main/src/clients/go](https://github.com/tigerbeetledb/tigerbeetle/tree/main/src/clients/go) for documentation and contributions.
EOF

git config --global user.email "bot@tigerbeetle.com"
git config --global user.name "TigerBeetle Bot"

cd ~/tigerbeetle-go
git add .
git add -f pkg

git commit -m "Autogenerated commit from tigerbeetledb/tigerbeetle@${GITHUB_SHA}"
git tag "tigerbeetle-${GITHUB_SHA}"

git push origin main
git push origin "tigerbeetle-${GITHUB_SHA}"
