## Converts the Advanced Message Queuing Protocol (AMQP) specification into Zig declarations.
## Usage: `python spec_parser.py amqp0-9-1.xml > spec.zig`
##
## Please refer to https://www.amqp.org/sites/amqp.org/files/amqp0-9-1.zip to download the
## specification XML and additional documentation.

import xml.etree.ElementTree as Tree
import sys

types = {
        'shortstr': "[]const u8",
        'longstr': "[]const u8",
        'bit': "bool",
        'octet': "u8",
        'short': "u16",
        'long': "u32",
        'longlong': "u64",
        'timestamp': "u64",
        'table': "Table",
    }

defaults = {
        '[]const u8': "\"\"",
        'bool': "false",
        'u8': "0",
        'u16': "0",
        'u32': "0",
        'u64': "0",
        'Table': "Table.init(&.{{}})",
    }

reader = {
        'octet': "read_int(u8)",
        'short': "read_int(u16)",
        'long': "read_int(u32)",
        'longlong': "read_int(u64)",
        'bit': "read_bitset()",
        'shortstr': 'read_short_string()',
        'longstr': 'read_long_string()',
        'table': "read_table()",
        'timestamp': 'read_int(u64)',
    }

writer = {
        'octet': "write_int(u8, ",
        'short': "write_int(u16, ",
        'long': "write_int(u32, ",
        'longlong': "write_int(u64, ",
        'bit': "write_int(u8, ",
        'shortstr': 'write_short_string(',
        'longstr': 'write_long_string(',
        'table': "write_table(",
        'timestamp': 'write_int(u64, ',
    }

def main(file):
    xml = Tree.parse(file)
    root = xml.getroot()
    if root.tag == 'amqp':
        for element in root.findall('domain'):
            domain = element.get('name')
            type = element.get('type')
            types[domain] = types[type]
            reader[domain] = reader[type]
            writer[domain] = writer[type]

        print(f"//////////////////////////////////////////////////////////")
        print(f"// This file was auto-generated by spec_parser.py       //")
        print(f"//              Do not manually modify.                 //")
        print(f"//////////////////////////////////////////////////////////")
        print(f"")
        print(f"const std = @import(\"std\");")
        print(f"const stdx = @import(\"../../../stdx.zig\");")
        print(f"const protocol = @import(\"protocol.zig\");")
        print(f"const Reader = protocol.Reader;")
        print(f"const Writer = protocol.Writer;")
        print(f"const Error = protocol.Error;")
        print(f"const Table = protocol.Table;")
        print(f"const MethodHeader = protocol.MethodHeader;")
        print(f"")
        constants(root)
        classes(root)
        receive_methods(root)
        send_methods(root)

def constants(root):
    constants = root.findall('constant')
    for element in constants:
        docs(element)
        name = element.get('name')
        class_attribute = element.get('class')
        name = f"{class_attribute}_{name}" if class_attribute else name
        print(f"pub const {to_upper_case(name)} = {element.get('value')};")

def classes(root):
    classes = root.findall('class')
    for element in classes:
        print(f"")
        docs(element)
        print(f"pub const {to_pascal_case(element.get('name'))} = struct {{")
        print(f"    pub const class = {element.get('index')};")
        methods(element)
        print(f"}};")

def methods(root):
    indent = "    "
    class_index = root.get('index')
    class_name = root.get('name')
    methods = root.findall('method')
    for element in methods:
        method = element.get('index')
        synchronous = 'true' if element.get('synchronous') == '1' else 'false'
        print(f"")
        docs(element, indent)
        print(f"{indent}pub const {to_pascal_case(element.get('name'))} = struct {{")
        print(f"{indent}    pub const header: MethodHeader = .{{ .class = {class_index}, .method = {method} }};")
        print(f"{indent}    pub const synchronous = {synchronous};")
        fields(element)
        read(element)
        write(class_name, element)
        print(f"{indent}}};")

def fields(root):
    indent = "        "
    fields = root.findall('field')
    for element in fields:
        print(f"")
        field = to_lower_case(element.get('name'))
        type = types[element.get('domain', element.get('type'))]
        default = f" = {defaults[type]}" if field.startswith('reserved') else ""
        docs(element, indent)
        print(f"{indent}{field}: {type}{default},")

def read(root):
    if root.find('chassis[@name="client"]') is None: return
    indent = "        "
    type = to_pascal_case(root.get('name'))
    print(f"")
    print(f"{indent}fn read(reader: *Reader) Error!{type} {{")
    fields = root.findall('field')
    if fields:
        bitset_octets = 0
        bitset_index = 0
        for element in fields:
            field = to_lower_case(element.get('name'))
            type = types[element.get('domain', element.get('type'))]
            read_function = reader[element.get('domain', element.get('type'))]
            if type == 'bool':
                if bitset_index == 0:
                    bitset_octets += 1
                    print(f"{indent}    const bitset_{bitset_octets} = try reader.{read_function};")
                print(f"{indent}    const {field} = bitset_{bitset_octets}.is_set({bitset_index});")
                bitset_index += 1
            else:
                print(f"{indent}    const {field} = try reader.{read_function};")
                bitset_index = 0
        print(f"");
        print(f"{indent}    return .{{")
        for element in fields:
            field = to_lower_case(element.get('name'))
            print(f"{indent}        .{field} = {field},")
        print(f"{indent}    }};")
    else:
        print(f"{indent}    _ = reader;")
        print(f"{indent}    return .{{}};")
    print(f"{indent}}}")

def write(class_name, root):
    if root.find('chassis[@name="server"]') is None: return
    indent = "        "
    enum_name = to_lower_case(class_name + '_' + root.get('name'))
    type = to_pascal_case(root.get('name'))
    print(f"")
    print(f"{indent}fn any(self: {type}) SendMethod {{")
    print(f"{indent}    return .{{ .{enum_name} = self }};")
    print(f"{indent}}}")
    print(f"")
    print(f"{indent}fn write(self: *const {type}, writer: *Writer) void {{")
    fields = root.findall('field')
    if fields:
        bitset_octets = 0
        bitset_index = 0
        for element in fields:
            field = to_lower_case(element.get('name'))
            type = types[element.get('domain', element.get('type'))]
            write_function = writer[element.get('domain', element.get('type'))]
            if type == 'bool':
                if bitset_index == 0:
                    bitset_octets += 1
                    print(f"{indent}    var bitset_{bitset_octets}: stdx.BitSetType(8) = .{{}};")
                print(f"{indent}    bitset_{bitset_octets}.set_value({bitset_index}, self.{field});")
                bitset_index += 1
            else:
                if bitset_index > 0:
                    print(f"{indent}    writer.{writer['bit']}bitset_{bitset_octets}.bits);")
                print(f"{indent}    writer.{write_function}self.{field});")
                bitset_index = 0
        if bitset_index > 0:
            print(f"{indent}    writer.{writer['bit']}bitset_{bitset_octets}.bits);")
    else:
        print(f"{indent}    _ = self;")
        print(f"{indent}    _ = writer;")
    print(f"{indent}}}")

def receive_methods(root):
    print(f"")
    print(f"/// Methods sent by the AMQP server that must be handled by the client side,")
    print(f"/// marked by the spec with `<chassis name=\"client\" implement=\"MUST|MAY\"/>`.")
    print(f"pub const ReceiveMethod = union(ReceiveMethod.Tag) {{")
    print(f"    pub const Tag = enum(u32) {{")
    classes = root.findall('class')
    for class_ in classes:
        methods = class_.findall('method')
        for method in methods:
            if method.find('chassis[@name="client"]') is None: continue
            class_name = to_pascal_case(class_.get('name'))
            method_name = to_pascal_case(method.get('name'))
            enum_name = to_lower_case(class_.get('name') + '_' + method.get('name'))
            print(f"        {enum_name} = @bitCast({class_name}.{method_name}.header),")
    print(f"    }};")
    print(f"")
    for class_ in classes:
        methods = class_.findall('method')
        for method in methods:
            if method.find('chassis[@name="client"]') is None: continue
            class_name = to_pascal_case(class_.get('name'))
            method_name = to_pascal_case(method.get('name'))
            enum_name = to_lower_case(class_.get('name') + '_' + method.get('name'))
            print(f"    {enum_name}: {class_name}.{method_name},")
    print(f"")
    print(f"    pub fn read(method_header: MethodHeader, reader: *Reader) Error!ReceiveMethod {{")
    print(f"        const tag: Tag = @enumFromInt(@as(u32, @bitCast(method_header)));")
    print(f"        const value: ReceiveMethod = switch (tag) {{")
    for class_ in classes:
        methods = class_.findall('method')
        for method in methods:
            if method.find('chassis[@name="client"]') is None: continue
            class_name = to_pascal_case(class_.get('name'))
            method_name = to_pascal_case(method.get('name'))
            enum_name = to_lower_case(class_.get('name') + '_' + method.get('name'))
            print(f"            .{enum_name} => .{{")
            print(f"                .{enum_name} = try {class_name}.{method_name}.read(reader),")
            print(f"            }},")
    print(f"        }};")
    print(f"        try reader.read_frame_end();")
    print(f"        return value;")
    print(f"    }}")
    print(f"}};")

def send_methods(root):
    # NB: The `protocol_header` case is hardcoded as it's not part of the spec
    # but behaves in the same way as methods.
    print(f"")
    print(f"/// Methods sent by the client, marked by the spec")
    print(f"/// with `<chassis name=\"server\" implement=\"MUST|MAY\"/>`.")
    print(f"pub const SendMethod = union(SendMethod.Tag) {{")
    print(f"    pub const Tag = enum(u32) {{")
    print(f"        protocol_header = 0,")
    classes = root.findall('class')
    for class_ in classes:
        methods = class_.findall('method')
        for method in methods:
            if method.find('chassis[@name="server"]') is None: continue
            class_name = to_pascal_case(class_.get('name'))
            method_name = to_pascal_case(method.get('name'))
            enum_name = to_lower_case(class_.get('name') + '_' + method.get('name'))
            print(f"        {enum_name} = @bitCast({class_name}.{method_name}.header),")
    print(f"    }};")
    print(f"")
    print(f"    protocol_header,")
    for class_ in classes:
        methods = class_.findall('method')
        for method in methods:
            if method.find('chassis[@name="server"]') is None: continue
            class_name = to_pascal_case(class_.get('name'))
            method_name = to_pascal_case(method.get('name'))
            enum_name = to_lower_case(class_.get('name') + '_' + method.get('name'))
            print(f"    {enum_name}: {class_name}.{method_name},")
    print(f"")

    print(f"    /// The expected response for synchronous methods,")
    print(f"    /// or `null` for asynchronous ones.")
    print(f"    pub fn response(self: SendMethod) ?ReceiveMethod.Tag {{")
    print(f"        return switch (self) {{")
    print(f"            .protocol_header => .connection_start,")
    for class_ in classes:
        methods = class_.findall('method')
        for method in methods:
            if method.find('chassis[@name="server"]') is None: continue
            response = method.find("response")
            if response is not None:
                send_enum_name = to_lower_case(class_.get('name') + '_' + method.get('name'))
                response_enum_name = to_lower_case(class_.get('name') + '_' + response.get('name'))
                print(f"            .{send_enum_name} => .{response_enum_name},")
    print(f"            else => null,")
    print(f"        }};")
    print(f"    }}")
    print(f"")

    print(f"    pub fn write(self: SendMethod, channel: u16, writer: *Writer) void {{")
    print(f"        switch (self) {{")
    print(f"            .protocol_header => {{")
    print(f"                const header: []const u8 = \"AMQP\\x00\\x00\\x09\\x01\";")
    print(f"                writer.write_body(header);")
    print(f"            }},")
    print(f"            inline else => |method| {{")
    print(f"                const frame_reference = writer.begin_frame(.{{")
    print(f"                    .type = .method,")
    print(f"                    .channel = channel,")
    print(f"                    .size = 0,")
    print(f"                }});")
    print(f"                const Method = @TypeOf(method);")
    print(f"                writer.write_method_header(Method.header);")
    print(f"                method.write(writer);")
    print(f"                writer.finish_frame(frame_reference);")
    print(f"            }},")
    print(f"        }}")
    print(f"    }}")
    print(f"}};")

def docs(element, indent=""):
    label = element.get('label')
    if label: print(f"{indent}/// {label.capitalize()}.")
    for doc in element.findall('doc'):
        if (doc.get('type') == 'grammar'): continue
        lines = doc.text.split("\n")
        for line in lines:
            line = line.strip()
            if line:
                print(f"{indent}/// {line}")

def to_upper_case(name):
    name = name.replace('-', '_').upper()
    return name

def to_lower_case(name):
    name = name.replace('-', '_').lower()
    return name

def to_pascal_case(name):
    name = ''.join([x.capitalize() for x in name.split('-')])
    return name

main(sys.argv[1])