// Code generated by "stringer -type=AccountResult -trimprefix=Account"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccountLinkedEventFailed-1]
	_ = x[AccountReservedFlag-2]
	_ = x[AccountReservedField-3]
	_ = x[AccountIdMustNotBeZero-4]
	_ = x[AccountLedgerMustNotBeZero-5]
	_ = x[AccountCodeMustNotBeZero-6]
	_ = x[AccountMutuallyExclusiveFlags-7]
	_ = x[AccountOverflowsDebits-8]
	_ = x[AccountOverflowsCredits-9]
	_ = x[AccountExceedsCredits-10]
	_ = x[AccountExceedsDebits-11]
	_ = x[AccountExistsWithDifferentFlags-12]
	_ = x[AccountExistsWithDifferentUserData-13]
	_ = x[AccountExistsWithDifferentLedger-14]
	_ = x[AccountExistsWithDifferentCode-15]
	_ = x[AccountExistsWithDifferentDebitsPending-16]
	_ = x[AccountExistsWithDifferentDebitsPosted-17]
	_ = x[AccountExistsWithDifferentCreditsPending-18]
	_ = x[AccountExistsWithDifferentCreditsPosted-19]
	_ = x[AccountExists-20]
	_ = x[accountResultSentinel-20]
}

const _AccountResult_name = "LinkedEventFailedReservedFlagReservedFieldIdMustNotBeZeroLedgerMustNotBeZeroCodeMustNotBeZeroMutuallyExclusiveFlagsOverflowsDebitsOverflowsCreditsExceedsCreditsExceedsDebitsExistsWithDifferentFlagsExistsWithDifferentUserDataExistsWithDifferentLedgerExistsWithDifferentCodeExistsWithDifferentDebitsPendingExistsWithDifferentDebitsPostedExistsWithDifferentCreditsPendingExistsWithDifferentCreditsPostedExists"

var _AccountResult_index = [...]uint16{0, 17, 29, 42, 57, 76, 93, 115, 130, 146, 160, 173, 197, 224, 249, 272, 304, 335, 368, 400, 406}

func (i AccountResult) String() string {
	i -= 1
	if i >= AccountResult(len(_AccountResult_index)-1) {
		return "AccountResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AccountResult_name[_AccountResult_index[i]:_AccountResult_index[i+1]]
}
