///////////////////////////////////////////////////////
// This file was auto-generated by go_bindings.zig   //
//              Do not manually modify.              //
///////////////////////////////////////////////////////

package types

/*
#include "../native/tb_client.h"
*/
import "C"
import "strconv"

type AccountFlags struct {
	Linked                     bool
	DebitsMustNotExceedCredits bool
	CreditsMustNotExceedDebits bool
}

func (f AccountFlags) ToUint16() uint16 {
	var ret uint16 = 0

	if f.Linked {
		ret |= (1 << 0)
	}

	if f.DebitsMustNotExceedCredits {
		ret |= (1 << 1)
	}

	if f.CreditsMustNotExceedDebits {
		ret |= (1 << 2)
	}

	return ret
}

type TransferFlags struct {
	Linked              bool
	Pending             bool
	PostPendingTransfer bool
	VoidPendingTransfer bool
	BalancingDebit      bool
	BalancingCredit     bool
}

func (f TransferFlags) ToUint16() uint16 {
	var ret uint16 = 0

	if f.Linked {
		ret |= (1 << 0)
	}

	if f.Pending {
		ret |= (1 << 1)
	}

	if f.PostPendingTransfer {
		ret |= (1 << 2)
	}

	if f.VoidPendingTransfer {
		ret |= (1 << 3)
	}

	if f.BalancingDebit {
		ret |= (1 << 4)
	}

	if f.BalancingCredit {
		ret |= (1 << 5)
	}

	return ret
}

type Account struct {
	ID             Uint128
	UserData       Uint128
	Reserved       [48]uint8
	Ledger         uint32
	Code           uint16
	Flags          uint16
	DebitsPending  uint64
	DebitsPosted   uint64
	CreditsPending uint64
	CreditsPosted  uint64
	Timestamp      uint64
}

func (o Account) AccountFlags() AccountFlags {
	var f AccountFlags
	f.Linked = ((o.Flags >> 0) & 0x1) == 1
	f.DebitsMustNotExceedCredits = ((o.Flags >> 1) & 0x1) == 1
	f.CreditsMustNotExceedDebits = ((o.Flags >> 2) & 0x1) == 1
	return f
}

type Transfer struct {
	ID              Uint128
	DebitAccountID  Uint128
	CreditAccountID Uint128
	UserData        Uint128
	Reserved        Uint128
	PendingID       Uint128
	Timeout         uint64
	Ledger          uint32
	Code            uint16
	Flags           uint16
	Amount          uint64
	Timestamp       uint64
}

func (o Transfer) TransferFlags() TransferFlags {
	var f TransferFlags
	f.Linked = ((o.Flags >> 0) & 0x1) == 1
	f.Pending = ((o.Flags >> 1) & 0x1) == 1
	f.PostPendingTransfer = ((o.Flags >> 2) & 0x1) == 1
	f.VoidPendingTransfer = ((o.Flags >> 3) & 0x1) == 1
	f.BalancingDebit = ((o.Flags >> 4) & 0x1) == 1
	f.BalancingCredit = ((o.Flags >> 5) & 0x1) == 1
	return f
}

type CreateAccountResult uint32

const (
	AccountOK                          CreateAccountResult = 0
	AccountLinkedEventFailed           CreateAccountResult = 1
	AccountLinkedEventChainOpen        CreateAccountResult = 2
	AccountTimestampMustBeZero         CreateAccountResult = 3
	AccountReservedFlag                CreateAccountResult = 4
	AccountReservedField               CreateAccountResult = 5
	AccountIDMustNotBeZero             CreateAccountResult = 6
	AccountIDMustNotBeIntMax           CreateAccountResult = 7
	AccountFlagsAreMutuallyExclusive   CreateAccountResult = 8
	AccountLedgerMustNotBeZero         CreateAccountResult = 9
	AccountCodeMustNotBeZero           CreateAccountResult = 10
	AccountDebitsPendingMustBeZero     CreateAccountResult = 11
	AccountDebitsPostedMustBeZero      CreateAccountResult = 12
	AccountCreditsPendingMustBeZero    CreateAccountResult = 13
	AccountCreditsPostedMustBeZero     CreateAccountResult = 14
	AccountExistsWithDifferentFlags    CreateAccountResult = 15
	AccountExistsWithDifferentUserData CreateAccountResult = 16
	AccountExistsWithDifferentLedger   CreateAccountResult = 17
	AccountExistsWithDifferentCode     CreateAccountResult = 18
	AccountExists                      CreateAccountResult = 19
)

func (i CreateAccountResult) String() string {
	switch i {
	case AccountOK:
		return "AccountOK"
	case AccountLinkedEventFailed:
		return "AccountLinkedEventFailed"
	case AccountLinkedEventChainOpen:
		return "AccountLinkedEventChainOpen"
	case AccountTimestampMustBeZero:
		return "AccountTimestampMustBeZero"
	case AccountReservedFlag:
		return "AccountReservedFlag"
	case AccountReservedField:
		return "AccountReservedField"
	case AccountIDMustNotBeZero:
		return "AccountIDMustNotBeZero"
	case AccountIDMustNotBeIntMax:
		return "AccountIDMustNotBeIntMax"
	case AccountFlagsAreMutuallyExclusive:
		return "AccountFlagsAreMutuallyExclusive"
	case AccountLedgerMustNotBeZero:
		return "AccountLedgerMustNotBeZero"
	case AccountCodeMustNotBeZero:
		return "AccountCodeMustNotBeZero"
	case AccountDebitsPendingMustBeZero:
		return "AccountDebitsPendingMustBeZero"
	case AccountDebitsPostedMustBeZero:
		return "AccountDebitsPostedMustBeZero"
	case AccountCreditsPendingMustBeZero:
		return "AccountCreditsPendingMustBeZero"
	case AccountCreditsPostedMustBeZero:
		return "AccountCreditsPostedMustBeZero"
	case AccountExistsWithDifferentFlags:
		return "AccountExistsWithDifferentFlags"
	case AccountExistsWithDifferentUserData:
		return "AccountExistsWithDifferentUserData"
	case AccountExistsWithDifferentLedger:
		return "AccountExistsWithDifferentLedger"
	case AccountExistsWithDifferentCode:
		return "AccountExistsWithDifferentCode"
	case AccountExists:
		return "AccountExists"
	}
	return "CreateAccountResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type CreateTransferResult uint32

const (
	TransferOK                                         CreateTransferResult = 0
	TransferLinkedEventFailed                          CreateTransferResult = 1
	TransferLinkedEventChainOpen                       CreateTransferResult = 2
	TransferTimestampMustBeZero                        CreateTransferResult = 3
	TransferReservedFlag                               CreateTransferResult = 4
	TransferReservedField                              CreateTransferResult = 5
	TransferIDMustNotBeZero                            CreateTransferResult = 6
	TransferIDMustNotBeIntMax                          CreateTransferResult = 7
	TransferFlagsAreMutuallyExclusive                  CreateTransferResult = 8
	TransferDebitAccountIDMustNotBeZero                CreateTransferResult = 9
	TransferDebitAccountIDMustNotBeIntMax              CreateTransferResult = 10
	TransferCreditAccountIDMustNotBeZero               CreateTransferResult = 11
	TransferCreditAccountIDMustNotBeIntMax             CreateTransferResult = 12
	TransferAccountsMustBeDifferent                    CreateTransferResult = 13
	TransferPendingIDMustBeZero                        CreateTransferResult = 14
	TransferPendingIDMustNotBeZero                     CreateTransferResult = 15
	TransferPendingIDMustNotBeIntMax                   CreateTransferResult = 16
	TransferPendingIDMustBeDifferent                   CreateTransferResult = 17
	TransferTimeoutReservedForPendingTransfer          CreateTransferResult = 18
	TransferLedgerMustNotBeZero                        CreateTransferResult = 19
	TransferCodeMustNotBeZero                          CreateTransferResult = 20
	TransferAmountMustNotBeZero                        CreateTransferResult = 21
	TransferDebitAccountNotFound                       CreateTransferResult = 22
	TransferCreditAccountNotFound                      CreateTransferResult = 23
	TransferAccountsMustHaveTheSameLedger              CreateTransferResult = 24
	TransferTransferMustHaveTheSameLedgerAsAccounts    CreateTransferResult = 25
	TransferPendingTransferNotFound                    CreateTransferResult = 26
	TransferPendingTransferNotPending                  CreateTransferResult = 27
	TransferPendingTransferHasDifferentDebitAccountID  CreateTransferResult = 28
	TransferPendingTransferHasDifferentCreditAccountID CreateTransferResult = 29
	TransferPendingTransferHasDifferentLedger          CreateTransferResult = 30
	TransferPendingTransferHasDifferentCode            CreateTransferResult = 31
	TransferExceedsPendingTransferAmount               CreateTransferResult = 32
	TransferPendingTransferHasDifferentAmount          CreateTransferResult = 33
	TransferPendingTransferAlreadyPosted               CreateTransferResult = 34
	TransferPendingTransferAlreadyVoided               CreateTransferResult = 35
	TransferPendingTransferExpired                     CreateTransferResult = 36
	TransferExistsWithDifferentFlags                   CreateTransferResult = 37
	TransferExistsWithDifferentDebitAccountID          CreateTransferResult = 38
	TransferExistsWithDifferentCreditAccountID         CreateTransferResult = 39
	TransferExistsWithDifferentPendingID               CreateTransferResult = 40
	TransferExistsWithDifferentUserData                CreateTransferResult = 41
	TransferExistsWithDifferentTimeout                 CreateTransferResult = 42
	TransferExistsWithDifferentCode                    CreateTransferResult = 43
	TransferExistsWithDifferentAmount                  CreateTransferResult = 44
	TransferExists                                     CreateTransferResult = 45
	TransferOverflowsDebitsPending                     CreateTransferResult = 46
	TransferOverflowsCreditsPending                    CreateTransferResult = 47
	TransferOverflowsDebitsPosted                      CreateTransferResult = 48
	TransferOverflowsCreditsPosted                     CreateTransferResult = 49
	TransferOverflowsDebits                            CreateTransferResult = 50
	TransferOverflowsCredits                           CreateTransferResult = 51
	TransferOverflowsTimeout                           CreateTransferResult = 52
	TransferExceedsCredits                             CreateTransferResult = 53
	TransferExceedsDebits                              CreateTransferResult = 54
)

func (i CreateTransferResult) String() string {
	switch i {
	case TransferOK:
		return "TransferOK"
	case TransferLinkedEventFailed:
		return "TransferLinkedEventFailed"
	case TransferLinkedEventChainOpen:
		return "TransferLinkedEventChainOpen"
	case TransferTimestampMustBeZero:
		return "TransferTimestampMustBeZero"
	case TransferReservedFlag:
		return "TransferReservedFlag"
	case TransferReservedField:
		return "TransferReservedField"
	case TransferIDMustNotBeZero:
		return "TransferIDMustNotBeZero"
	case TransferIDMustNotBeIntMax:
		return "TransferIDMustNotBeIntMax"
	case TransferFlagsAreMutuallyExclusive:
		return "TransferFlagsAreMutuallyExclusive"
	case TransferDebitAccountIDMustNotBeZero:
		return "TransferDebitAccountIDMustNotBeZero"
	case TransferDebitAccountIDMustNotBeIntMax:
		return "TransferDebitAccountIDMustNotBeIntMax"
	case TransferCreditAccountIDMustNotBeZero:
		return "TransferCreditAccountIDMustNotBeZero"
	case TransferCreditAccountIDMustNotBeIntMax:
		return "TransferCreditAccountIDMustNotBeIntMax"
	case TransferAccountsMustBeDifferent:
		return "TransferAccountsMustBeDifferent"
	case TransferPendingIDMustBeZero:
		return "TransferPendingIDMustBeZero"
	case TransferPendingIDMustNotBeZero:
		return "TransferPendingIDMustNotBeZero"
	case TransferPendingIDMustNotBeIntMax:
		return "TransferPendingIDMustNotBeIntMax"
	case TransferPendingIDMustBeDifferent:
		return "TransferPendingIDMustBeDifferent"
	case TransferTimeoutReservedForPendingTransfer:
		return "TransferTimeoutReservedForPendingTransfer"
	case TransferLedgerMustNotBeZero:
		return "TransferLedgerMustNotBeZero"
	case TransferCodeMustNotBeZero:
		return "TransferCodeMustNotBeZero"
	case TransferAmountMustNotBeZero:
		return "TransferAmountMustNotBeZero"
	case TransferDebitAccountNotFound:
		return "TransferDebitAccountNotFound"
	case TransferCreditAccountNotFound:
		return "TransferCreditAccountNotFound"
	case TransferAccountsMustHaveTheSameLedger:
		return "TransferAccountsMustHaveTheSameLedger"
	case TransferTransferMustHaveTheSameLedgerAsAccounts:
		return "TransferTransferMustHaveTheSameLedgerAsAccounts"
	case TransferPendingTransferNotFound:
		return "TransferPendingTransferNotFound"
	case TransferPendingTransferNotPending:
		return "TransferPendingTransferNotPending"
	case TransferPendingTransferHasDifferentDebitAccountID:
		return "TransferPendingTransferHasDifferentDebitAccountID"
	case TransferPendingTransferHasDifferentCreditAccountID:
		return "TransferPendingTransferHasDifferentCreditAccountID"
	case TransferPendingTransferHasDifferentLedger:
		return "TransferPendingTransferHasDifferentLedger"
	case TransferPendingTransferHasDifferentCode:
		return "TransferPendingTransferHasDifferentCode"
	case TransferExceedsPendingTransferAmount:
		return "TransferExceedsPendingTransferAmount"
	case TransferPendingTransferHasDifferentAmount:
		return "TransferPendingTransferHasDifferentAmount"
	case TransferPendingTransferAlreadyPosted:
		return "TransferPendingTransferAlreadyPosted"
	case TransferPendingTransferAlreadyVoided:
		return "TransferPendingTransferAlreadyVoided"
	case TransferPendingTransferExpired:
		return "TransferPendingTransferExpired"
	case TransferExistsWithDifferentFlags:
		return "TransferExistsWithDifferentFlags"
	case TransferExistsWithDifferentDebitAccountID:
		return "TransferExistsWithDifferentDebitAccountID"
	case TransferExistsWithDifferentCreditAccountID:
		return "TransferExistsWithDifferentCreditAccountID"
	case TransferExistsWithDifferentPendingID:
		return "TransferExistsWithDifferentPendingID"
	case TransferExistsWithDifferentUserData:
		return "TransferExistsWithDifferentUserData"
	case TransferExistsWithDifferentTimeout:
		return "TransferExistsWithDifferentTimeout"
	case TransferExistsWithDifferentCode:
		return "TransferExistsWithDifferentCode"
	case TransferExistsWithDifferentAmount:
		return "TransferExistsWithDifferentAmount"
	case TransferExists:
		return "TransferExists"
	case TransferOverflowsDebitsPending:
		return "TransferOverflowsDebitsPending"
	case TransferOverflowsCreditsPending:
		return "TransferOverflowsCreditsPending"
	case TransferOverflowsDebitsPosted:
		return "TransferOverflowsDebitsPosted"
	case TransferOverflowsCreditsPosted:
		return "TransferOverflowsCreditsPosted"
	case TransferOverflowsDebits:
		return "TransferOverflowsDebits"
	case TransferOverflowsCredits:
		return "TransferOverflowsCredits"
	case TransferOverflowsTimeout:
		return "TransferOverflowsTimeout"
	case TransferExceedsCredits:
		return "TransferExceedsCredits"
	case TransferExceedsDebits:
		return "TransferExceedsDebits"
	}
	return "CreateTransferResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
}

type AccountEventResult struct {
	Index  uint32
	Result CreateAccountResult
}

type TransferEventResult struct {
	Index  uint32
	Result CreateTransferResult
}

