// Code generated by "stringer -type=CreateTransferResult -trimprefix=Transfer"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransferLinkedEventFailed-1]
	_ = x[TransferLinkedEventChainOpen-2]
	_ = x[TransferReservedFlag-3]
	_ = x[TransferReservedField-4]
	_ = x[TransferIdMustNotBeZero-5]
	_ = x[TransferIdMustNotBeIntMax-6]
	_ = x[TransferDebitAccountIdMustNotBeZero-7]
	_ = x[TransferDebitAccountIdMustNotBeIntMax-8]
	_ = x[TransferCreditAccountIdMustNotBeZero-9]
	_ = x[TransferCreditAccountIdMustNotBeIntMax-10]
	_ = x[TransferAccountsMustBeDifferent-11]
	_ = x[TransferPendingIdMustBeZero-12]
	_ = x[TransferPendingTransferMustTimeout-13]
	_ = x[TransferLedgerMustNotBeZero-14]
	_ = x[TransferCodeMustNotBeZero-15]
	_ = x[TransferAmountMustNotBeZero-16]
	_ = x[TransferDebitAccountNotFound-17]
	_ = x[TransferCreditAccountNotFound-18]
	_ = x[TransferAccountsMustHaveTheSameLedger-19]
	_ = x[TransferTransferMustHaveTheSameLedgerAsAccounts-20]
	_ = x[TransferExistsWithDifferentFlags-21]
	_ = x[TransferExistsWithDifferentDebitAccountId-22]
	_ = x[TransferExistsWithDifferentCreditAccountId-23]
	_ = x[TransferExistsWithDifferentUserData-24]
	_ = x[TransferExistsWithDifferentPendingId-25]
	_ = x[TransferExistsWithDifferentTimeout-26]
	_ = x[TransferExistsWithDifferentCode-27]
	_ = x[TransferExistsWithDifferentAmount-28]
	_ = x[TransferExists-29]
	_ = x[TransferOverflowsDebitsPending-30]
	_ = x[TransferOverflowsCreditsPending-31]
	_ = x[TransferOverflowsDebitsPosted-32]
	_ = x[TransferOverflowsCreditsPosted-33]
	_ = x[TransferOverflowsDebits-34]
	_ = x[TransferOverflowsCredits-35]
	_ = x[TransferExceedsCredits-36]
	_ = x[TransferExceedsDebits-37]
	_ = x[TransferCannotPostAndVoidPendingTransfer-38]
	_ = x[TransferPendingTransferCannotPostOrVoidAnother-39]
	_ = x[TransferTimeoutReservedForPendingTransfer-40]
	_ = x[TransferPendingIdMustNotBeZero-41]
	_ = x[TransferPendingIdMustNotBeIntMax-42]
	_ = x[TransferPendingIdMustBeDifferent-43]
	_ = x[TransferPendingTransferNotFound-44]
	_ = x[TransferPendingTransferNotPending-45]
	_ = x[TransferPendingTransferHasDifferentDebitAccountId-46]
	_ = x[TransferPendingTransferHasDifferentCreditAccountId-47]
	_ = x[TransferPendingTransferHasDifferentLedger-48]
	_ = x[TransferPendingTransferHasDifferentCode-49]
	_ = x[TransferExceedsPendingTransferAmount-50]
	_ = x[TransferPendingTransferHasDifferentAmount-51]
	_ = x[TransferPendingTransferAlreadyPosted-52]
	_ = x[TransferPendingTransferAlreadyVoided-53]
	_ = x[TransferPendingTransferExpired-54]
}

const _CreateTransferResult_name = "LinkedEventFailedLinkedEventChainOpenReservedFlagReservedFieldIdMustNotBeZeroIdMustNotBeIntMaxDebitAccountIdMustNotBeZeroDebitAccountIdMustNotBeIntMaxCreditAccountIdMustNotBeZeroCreditAccountIdMustNotBeIntMaxAccountsMustBeDifferentPendingIdMustBeZeroPendingTransferMustTimeoutLedgerMustNotBeZeroCodeMustNotBeZeroAmountMustNotBeZeroDebitAccountNotFoundCreditAccountNotFoundAccountsMustHaveTheSameLedgerTransferMustHaveTheSameLedgerAsAccountsExistsWithDifferentFlagsExistsWithDifferentDebitAccountIdExistsWithDifferentCreditAccountIdExistsWithDifferentUserDataExistsWithDifferentPendingIdExistsWithDifferentTimeoutExistsWithDifferentCodeExistsWithDifferentAmountExistsOverflowsDebitsPendingOverflowsCreditsPendingOverflowsDebitsPostedOverflowsCreditsPostedOverflowsDebitsOverflowsCreditsExceedsCreditsExceedsDebitsCannotPostAndVoidPendingTransferPendingTransferCannotPostOrVoidAnotherTimeoutReservedForPendingTransferPendingIdMustNotBeZeroPendingIdMustNotBeIntMaxPendingIdMustBeDifferentPendingTransferNotFoundPendingTransferNotPendingPendingTransferHasDifferentDebitAccountIdPendingTransferHasDifferentCreditAccountIdPendingTransferHasDifferentLedgerPendingTransferHasDifferentCodeExceedsPendingTransferAmountPendingTransferHasDifferentAmountPendingTransferAlreadyPostedPendingTransferAlreadyVoidedPendingTransferExpired"

var _CreateTransferResult_index = [...]uint16{0, 17, 37, 49, 62, 77, 94, 121, 150, 178, 208, 231, 250, 276, 295, 312, 331, 351, 372, 401, 440, 464, 497, 531, 558, 586, 612, 635, 660, 666, 688, 711, 732, 754, 769, 785, 799, 812, 844, 882, 915, 937, 961, 985, 1008, 1033, 1074, 1116, 1149, 1180, 1208, 1241, 1269, 1297, 1319}

func (i CreateTransferResult) String() string {
	i -= 1
	if i >= CreateTransferResult(len(_CreateTransferResult_index)-1) {
		return "CreateTransferResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CreateTransferResult_name[_CreateTransferResult_index[i]:_CreateTransferResult_index[i+1]]
}
