// Code generated by "stringer -type=TransferResult -trimprefix=Transfer"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransferLinkedEventFailed-1]
	_ = x[TransferReservedFlag-2]
	_ = x[TransferReservedField-3]
	_ = x[TransferIdMustNotBeZero-4]
	_ = x[TransferDebitAccountIdMustNotBeZero-5]
	_ = x[TransferCreditAccountIdMustNotBeZero-6]
	_ = x[TransferAccountsMustBeDifferent-7]
	_ = x[TransferPendingIdMustBeZero-8]
	_ = x[TransferPendingTransferMustTimeout-9]
	_ = x[TransferLedgerMustNotBeZero-10]
	_ = x[TransferCodeMustNotBeZero-11]
	_ = x[TransferAmountMustNotBeZero-12]
	_ = x[TransferDebitAccountNotFound-13]
	_ = x[TransferCreditAccountNotFound-14]
	_ = x[TransferAccountsMustHaveTheSameLedger-15]
	_ = x[TransferTransferMustHaveTheSameLedgerAsAccounts-16]
	_ = x[TransferExistsWithDifferentFlags-17]
	_ = x[TransferExistsWithDifferentDebitAccountId-18]
	_ = x[TransferExistsWithDifferentCreditAccountId-19]
	_ = x[TransferExistsWithDifferentUserData-20]
	_ = x[TransferExistsWithDifferentPendingId-21]
	_ = x[TransferExistsWithDifferentTimeout-22]
	_ = x[TransferExistsWithDifferentCode-23]
	_ = x[TransferExistsWithDifferentAmount-24]
	_ = x[TransferExists-25]
	_ = x[TransferOverflowsDebitsPending-26]
	_ = x[TransferOverflowsCreditsPending-27]
	_ = x[TransferOverflowsDebitsPosted-28]
	_ = x[TransferOverflowsCreditsPosted-29]
	_ = x[TransferOverflowsDebits-30]
	_ = x[TransferOverflowsCredits-31]
	_ = x[TransferExceedsCredits-32]
	_ = x[TransferExceedsDebits-33]
	_ = x[TransferCannotPostAndVoidPendingTransfer-34]
	_ = x[TransferPendingTransferCannotPostOrVoidAnother-35]
	_ = x[TransferTimeoutReservedForPendingTransfer-36]
	_ = x[TransferPendingIdMustNotBeZero-37]
	_ = x[TransferPendingIdMustBeDifferent-38]
	_ = x[TransferPendingTransferNotFound-39]
	_ = x[TransferPendingTransferNotPending-40]
	_ = x[TransferPendingTransferHasDifferentDebitAccountId-41]
	_ = x[TransferPendingTransferHasDifferentCreditAccountId-42]
	_ = x[TransferPendingTransferHasDifferentLedger-43]
	_ = x[TransferPendingTransferHasDifferentCode-44]
	_ = x[TransferExceedsPendingTransferAmount-45]
	_ = x[TransferPendingTransferHasDifferentAmount-46]
	_ = x[TransferPendingTransferAlreadyPosted-47]
	_ = x[TransferPendingTransferAlreadyVoided-48]
	_ = x[TransferPendingTransferExpired-49]
}

const _TransferResult_name = "LinkedEventFailedReservedFlagReservedFieldIdMustNotBeZeroDebitAccountIdMustNotBeZeroCreditAccountIdMustNotBeZeroAccountsMustBeDifferentPendingIdMustBeZeroPendingTransferMustTimeoutLedgerMustNotBeZeroCodeMustNotBeZeroAmountMustNotBeZeroDebitAccountNotFoundCreditAccountNotFoundAccountsMustHaveTheSameLedgerTransferMustHaveTheSameLedgerAsAccountsExistsWithDifferentFlagsExistsWithDifferentDebitAccountIdExistsWithDifferentCreditAccountIdExistsWithDifferentUserDataExistsWithDifferentPendingIdExistsWithDifferentTimeoutExistsWithDifferentCodeExistsWithDifferentAmountExistsOverflowsDebitsPendingOverflowsCreditsPendingOverflowsDebitsPostedOverflowsCreditsPostedOverflowsDebitsOverflowsCreditsExceedsCreditsExceedsDebitsCannotPostAndVoidPendingTransferPendingTransferCannotPostOrVoidAnotherTimeoutReservedForPendingTransferPendingIdMustNotBeZeroPendingIdMustBeDifferentPendingTransferNotFoundPendingTransferNotPendingPendingTransferHasDifferentDebitAccountIdPendingTransferHasDifferentCreditAccountIdPendingTransferHasDifferentLedgerPendingTransferHasDifferentCodeExceedsPendingTransferAmountPendingTransferHasDifferentAmountPendingTransferAlreadyPostedPendingTransferAlreadyVoidedPendingTransferExpired"

var _TransferResult_index = [...]uint16{0, 17, 29, 42, 57, 84, 112, 135, 154, 180, 199, 216, 235, 255, 276, 305, 344, 368, 401, 435, 462, 490, 516, 539, 564, 570, 592, 615, 636, 658, 673, 689, 703, 716, 748, 786, 819, 841, 865, 888, 913, 954, 996, 1029, 1060, 1088, 1121, 1149, 1177, 1199}

func (i TransferResult) String() string {
	i -= 1
	if i >= TransferResult(len(_TransferResult_index)-1) {
		return "TransferResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TransferResult_name[_TransferResult_index[i]:_TransferResult_index[i+1]]
}
