require "minitest/test_task"

EXT_DIR = File.expand_path("src/ext/tigerbeetle", __dir__)
PROJECT_ROOT = File.expand_path("../../..", __dir__)

task(:generate) do
  zig = ENV.fetch("ZIG_EXE") { File.join(PROJECT_ROOT, "zig", "zig") }
  sh(zig, "build", "clients:ruby", chdir: PROJECT_ROOT)
end

desc("Build the C extension")
task(:ext_compile) do
  Rake::Task[:generate].invoke unless ENV.key?("CI")
  sh("ruby extconf.rb && make", chdir: EXT_DIR)
end

namespace(:test) do
  Minitest::TestTask.create(:unit) do |t|
    t.libs = [".", "src", "src/ext"]
    t.test_globs = ["tests/unit/**/*.rb"]
  end

  task(unit: :ext_compile)

  Minitest::TestTask.create(:integration) do |t|
    t.libs = [".", "src", "src/ext"]
    t.test_globs = ["tests/integration/**/*.rb"]
  end

  task(integration: :ext_compile)
end

task(default: "test:unit")
