const std = @import("std");
const assert = std.debug.assert;

const vsr = @import("vsr");
const exports = vsr.tb_client.exports;
const tb = vsr.tigerbeetle;

const flag_mappings = .{
    .{ tb.AccountFlags, "AccountFlags" },
    .{ tb.TransferFlags, "TransferFlags" },
    .{ tb.AccountFilterFlags, "AccountFilterFlags" },
    .{ tb.QueryFilterFlags, "QueryFilterFlags" },
};

const Buffer = struct {
    inner: std.ArrayList(u8),

    pub fn init(allocator: std.mem.Allocator) Buffer {
        return .{ .inner = std.ArrayList(u8).init(allocator) };
    }

    pub fn print(self: *Buffer, comptime format: []const u8, args: anytype) void {
        self.inner.writer().print(format, args) catch unreachable;
    }
};

fn to_upper_snake(comptime input: []const u8) [input.len]u8 {
    comptime var output: [input.len]u8 = undefined;
    inline for (&output, 0..) |*c, i| {
        c.* = input[i];
        c.* -= 32 * @as(u8, @intFromBool(c.* >= 'a' and c.* <= 'z'));
    }
    return output;
}

fn ruby_flags_name_from_type(comptime Type: type) ?[]const u8 {
    comptime for (flag_mappings) |mapping| {
        const ZigType, const ruby_name = mapping;
        if (Type == ZigType) return ruby_name;
    };
    return null;
}

fn emit_flags_module(
    buffer: *Buffer,
    comptime Type: type,
    comptime ruby_name: []const u8,
) void {
    assert(@typeInfo(Type) == .@"struct");
    assert(@typeInfo(Type).@"struct".layout == .@"packed");

    buffer.print("  module {s}\n", .{ruby_name});
    buffer.print("    NONE = 0\n", .{});
    inline for (@typeInfo(Type).@"struct".fields, 0..) |field, i| {
        if (comptime std.mem.startsWith(u8, field.name, "deprecated_")) continue;
        if (comptime std.mem.eql(u8, field.name, "padding")) continue;
        const upper_snake = to_upper_snake(field.name);
        buffer.print("    {s} = 1 << {d}\n", .{ @as([]const u8, &upper_snake), i });
    }
    buffer.print("  end\n\n", .{});
}

fn emit_enum_module(
    buffer: *Buffer,
    comptime Type: type,
    comptime ruby_name: []const u8,
    comptime skip_fields: []const []const u8,
) void {
    assert(@typeInfo(Type) == .@"enum");

    buffer.print("  module {s}\n", .{ruby_name});
    inline for (@typeInfo(Type).@"enum".fields) |field| {
        if (comptime std.mem.startsWith(u8, field.name, "deprecated_")) continue;
        comptime var skip = false;
        inline for (skip_fields) |sf| {
            skip = skip or comptime std.mem.eql(u8, sf, field.name);
        }
        if (skip) continue;
        const upper_snake = to_upper_snake(field.name);
        const value: u64 = @intCast(@intFromEnum(@field(Type, field.name)));
        buffer.print("    {s} = {d}\n", .{ @as([]const u8, &upper_snake), value });
    }
    buffer.print("  end\n\n", .{});
}

fn emit_struct_class(
    buffer: *Buffer,
    comptime Type: type,
    comptime ruby_name: []const u8,
    comptime read_only: bool,
) void {
    assert(@typeInfo(Type) == .@"struct");
    assert(@typeInfo(Type).@"struct".layout == .@"extern");

    const fields = @typeInfo(Type).@"struct".fields;

    buffer.print("  class {s}\n", .{ruby_name});

    inline for (fields) |field| {
        if (comptime std.mem.eql(u8, field.name, "reserved")) continue;
        buffer.print("    attr_{s} :{s}\n", .{ if (read_only) "reader" else "accessor", field.name });
    }
    buffer.print("\n", .{});

    buffer.print("    def initialize\n", .{});
    inline for (fields) |field| {
        if (comptime std.mem.eql(u8, field.name, "reserved")) continue;
        const field_type_info = @typeInfo(field.type);
        const is_flags = field_type_info == .@"struct" and
            field_type_info.@"struct".layout == .@"packed";
        if (is_flags) {
            const flags_ruby_name = comptime ruby_flags_name_from_type(field.type).?;
            buffer.print("      @{s} = {s}::NONE\n", .{ field.name, flags_ruby_name });
        } else {
            buffer.print("      @{s} = 0\n", .{field.name});
        }
    }
    if (!read_only) {
        buffer.print("\n      yield self if block_given?\n", .{});
    }
    buffer.print("    end\n", .{});
    buffer.print("  end\n\n", .{});
}

pub fn main() !void {
    @setEvalBranchQuota(100_000);

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = arena.allocator();

    var buffer = Buffer.init(allocator);

    buffer.print(
        \\########################################################
        \\## This file was auto-generated by ruby_bindings.zig ##
        \\##              Do not manually modify.              ##
        \\########################################################
        \\
        \\module TigerBeetle
        \\
    , .{});

    // Flag modules (packed structs).
    inline for (flag_mappings) |mapping| {
        const ZigType, const ruby_name = mapping;
        emit_flags_module(&buffer, ZigType, ruby_name);
    }

    // Operation constants.
    emit_enum_module(&buffer, exports.tb_operation, "Operation", &.{
        "reserved", "root", "register", "pulse", "get_change_events",
    });

    // Status constants.
    emit_enum_module(&buffer, tb.CreateAccountStatus, "CreateAccountStatus", &.{});
    emit_enum_module(&buffer, tb.CreateTransferStatus, "CreateTransferStatus", &.{});

    // Struct classes — input types (read-write, yield self).
    emit_struct_class(&buffer, tb.Account, "Account", false);
    emit_struct_class(&buffer, tb.Transfer, "Transfer", false);
    emit_struct_class(&buffer, tb.AccountFilter, "AccountFilter", false);
    emit_struct_class(&buffer, tb.QueryFilter, "QueryFilter", false);

    // Struct classes — response-only types (read-only, no yield).
    emit_struct_class(&buffer, tb.AccountBalance, "AccountBalance", true);
    emit_struct_class(&buffer, tb.CreateAccountResult, "CreateAccountResult", true);
    emit_struct_class(&buffer, tb.CreateTransferResult, "CreateTransferResult", true);

    buffer.print("end\n", .{});

    try std.io.getStdOut().writeAll(buffer.inner.items);
}
