FROM node:12.16.0-alpine as builder
WORKDIR /opt/tiger-beetle

RUN apk add --no-cache -t build-dependencies python make gcc g++ libtool autoconf automake

COPY package.json package-lock.json* /opt/tiger-beetle/

RUN npm install

FROM node:12.16.0-alpine
WORKDIR /opt/tiger-beetle

COPY --from=builder /opt/tiger-beetle .

WORKDIR /opt/tiger-beetle

COPY client.js .
COPY fast-ml-api-adapter.js .
COPY log-event.js .
COPY uuid4.js .
COPY index.js .

EXPOSE 30000

CMD ["npm", "run", "start:fast-ml-api-adapter"]