//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

public interface AccountFlags {
    int NONE = (int) 0;

    /**
     * @see https://docs.tigerbeetle.com/reference/accounts#flagslinked
     */
    int LINKED = (int) (1 << 0);

    /**
     * @see https://docs.tigerbeetle.com/reference/accounts#flagsdebits_must_not_exceed_credits
     */
    int DEBITS_MUST_NOT_EXCEED_CREDITS = (int) (1 << 1);

    /**
     * @see https://docs.tigerbeetle.com/reference/accounts#flagscredits_must_not_exceed_debits
     */
    int CREDITS_MUST_NOT_EXCEED_DEBITS = (int) (1 << 2);

    static boolean hasLinked(final int flags) {
        return (flags & LINKED) == LINKED;
    }

    static boolean hasDebitsMustNotExceedCredits(final int flags) {
        return (flags & DEBITS_MUST_NOT_EXCEED_CREDITS) == DEBITS_MUST_NOT_EXCEED_CREDITS;
    }

    static boolean hasCreditsMustNotExceedDebits(final int flags) {
        return (flags & CREDITS_MUST_NOT_EXCEED_DEBITS) == CREDITS_MUST_NOT_EXCEED_DEBITS;
    }

}
