//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

public interface AccountFlags {
    int NONE = (int) 0;

    /**
     * @see <a href="https://docs.tigerbeetle.com/reference/account#flagslinked">linked</a>
     */
    int LINKED = (int) (1 << 0);

    /**
     * @see <a href="https://docs.tigerbeetle.com/reference/account#flagsdebits_must_not_exceed_credits">debits_must_not_exceed_credits</a>
     */
    int DEBITS_MUST_NOT_EXCEED_CREDITS = (int) (1 << 1);

    /**
     * @see <a href="https://docs.tigerbeetle.com/reference/account#flagscredits_must_not_exceed_debits">credits_must_not_exceed_debits</a>
     */
    int CREDITS_MUST_NOT_EXCEED_DEBITS = (int) (1 << 2);

    /**
     * @see <a href="https://docs.tigerbeetle.com/reference/account#flagshistory">history</a>
     */
    int HISTORY = (int) (1 << 3);

    static boolean hasLinked(final int flags) {
        return (flags & LINKED) == LINKED;
    }

    static boolean hasDebitsMustNotExceedCredits(final int flags) {
        return (flags & DEBITS_MUST_NOT_EXCEED_CREDITS) == DEBITS_MUST_NOT_EXCEED_CREDITS;
    }

    static boolean hasCreditsMustNotExceedDebits(final int flags) {
        return (flags & CREDITS_MUST_NOT_EXCEED_DEBITS) == CREDITS_MUST_NOT_EXCEED_DEBITS;
    }

    static boolean hasHistory(final int flags) {
        return (flags & HISTORY) == HISTORY;
    }

}
