//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

public enum CreateTransferResult {

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#ok
     */
    Ok((int) 0),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#linked_event_failed
     */
    LinkedEventFailed((int) 1),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#linked_event_chain_open
     */
    LinkedEventChainOpen((int) 2),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#reserved_flag
     */
    ReservedFlag((int) 3),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#reserved_field
     */
    ReservedField((int) 4),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#id_must_not_be_zero
     */
    IdMustNotBeZero((int) 5),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#id_must_not_be_int_max
     */
    IdMustNotBeIntMax((int) 6),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#debit_account_id_must_not_be_zero
     */
    DebitAccountIdMustNotBeZero((int) 7),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#debit_account_id_must_not_be_int_max
     */
    DebitAccountIdMustNotBeIntMax((int) 8),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#credit_account_id_must_not_be_zero
     */
    CreditAccountIdMustNotBeZero((int) 9),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#credit_account_id_must_not_be_int_max
     */
    CreditAccountIdMustNotBeIntMax((int) 10),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#accounts_must_be_different
     */
    AccountsMustBeDifferent((int) 11),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_id_must_be_zero
     */
    PendingIdMustBeZero((int) 12),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#ledger_must_not_be_zero
     */
    LedgerMustNotBeZero((int) 13),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#code_must_not_be_zero
     */
    CodeMustNotBeZero((int) 14),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#amount_must_not_be_zero
     */
    AmountMustNotBeZero((int) 15),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#debit_account_not_found
     */
    DebitAccountNotFound((int) 16),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#credit_account_not_found
     */
    CreditAccountNotFound((int) 17),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#accounts_must_have_the_same_ledger
     */
    AccountsMustHaveTheSameLedger((int) 18),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#transfer_must_have_the_same_ledger_as_accounts
     */
    TransferMustHaveTheSameLedgerAsAccounts((int) 19),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_flags
     */
    ExistsWithDifferentFlags((int) 20),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_debit_account_id
     */
    ExistsWithDifferentDebitAccountId((int) 21),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_credit_account_id
     */
    ExistsWithDifferentCreditAccountId((int) 22),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_user_data
     */
    ExistsWithDifferentUserData((int) 23),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_pending_id
     */
    ExistsWithDifferentPendingId((int) 24),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_timeout
     */
    ExistsWithDifferentTimeout((int) 25),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_code
     */
    ExistsWithDifferentCode((int) 26),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists_with_different_amount
     */
    ExistsWithDifferentAmount((int) 27),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exists
     */
    Exists((int) 28),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_debits_pending
     */
    OverflowsDebitsPending((int) 29),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_credits_pending
     */
    OverflowsCreditsPending((int) 30),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_debits_posted
     */
    OverflowsDebitsPosted((int) 31),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_credits_posted
     */
    OverflowsCreditsPosted((int) 32),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_debits
     */
    OverflowsDebits((int) 33),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_credits
     */
    OverflowsCredits((int) 34),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#overflows_timeout
     */
    OverflowsTimeout((int) 35),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exceeds_credits
     */
    ExceedsCredits((int) 36),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exceeds_debits
     */
    ExceedsDebits((int) 37),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#cannot_post_and_void_pending_transfer
     */
    CannotPostAndVoidPendingTransfer((int) 38),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_cannot_post_or_void_another
     */
    PendingTransferCannotPostOrVoidAnother((int) 39),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#timeout_reserved_for_pending_transfer
     */
    TimeoutReservedForPendingTransfer((int) 40),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_id_must_not_be_zero
     */
    PendingIdMustNotBeZero((int) 41),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_id_must_not_be_int_max
     */
    PendingIdMustNotBeIntMax((int) 42),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_id_must_be_different
     */
    PendingIdMustBeDifferent((int) 43),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_not_found
     */
    PendingTransferNotFound((int) 44),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_not_pending
     */
    PendingTransferNotPending((int) 45),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_has_different_debit_account_id
     */
    PendingTransferHasDifferentDebitAccountId((int) 46),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_has_different_credit_account_id
     */
    PendingTransferHasDifferentCreditAccountId((int) 47),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_has_different_ledger
     */
    PendingTransferHasDifferentLedger((int) 48),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_has_different_code
     */
    PendingTransferHasDifferentCode((int) 49),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#exceeds_pending_transfer_amount
     */
    ExceedsPendingTransferAmount((int) 50),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_has_different_amount
     */
    PendingTransferHasDifferentAmount((int) 51),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_already_posted
     */
    PendingTransferAlreadyPosted((int) 52),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_already_voided
     */
    PendingTransferAlreadyVoided((int) 53),

    /**
     * @see https://docs.tigerbeetle.com/reference/operations/create_transfers#pending_transfer_expired
     */
    PendingTransferExpired((int) 54);

    public final int value;

    private CreateTransferResult(int value) {
        this.value = value;
    }

    public static CreateTransferResult fromValue(int value) {
        var values = CreateTransferResult.values();
        if (value < 0 || value >= values.length)
            throw new IllegalArgumentException(
                    String.format("Invalid CreateTransferResult value=%d", value));

        return values[value];
    }
}

