//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

public enum InitializationStatus {
    Success((int) 0),
    Unexpected((int) 1),
    OutOfMemory((int) 2),
    AddressInvalid((int) 3),
    AddressLimitExceeded((int) 4),
    SystemResources((int) 5),
    NetworkSubsystem((int) 6);

    public final int value;

    static final InitializationStatus[] enumByValue;
    static {
    final var values = values();
      enumByValue = new InitializationStatus[values.length];
       for (final var item : values) {
          enumByValue[item.value] = item;
      }
    }

    InitializationStatus(int value) {
        this.value = value;
    }

    public static InitializationStatus fromValue(int value) {
        if (value < 0 || value >= enumByValue.length)
            throw new IllegalArgumentException(
                    String.format("Invalid InitializationStatus value=%d", value));

        final var item = enumByValue[value];
        AssertionError.assertTrue(item.value == value,
          "Unexpected InitializationStatus: found=%d expected=%d", item.value, value);
        return item;
    }
}

