//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;
import java.util.HashMap;

public enum InitializationStatus {
    Success((int) 0),
    Unexpected((int) 1),
    OutOfMemory((int) 2),
    AddressInvalid((int) 3),
    AddressLimitExceeded((int) 4),
    SystemResources((int) 5),
    NetworkSubsystem((int) 6);

    public final int value;

    static final HashMap<Object, InitializationStatus> enumByValue;
    static {
    final var values = values();
      enumByValue = new HashMap<Object, InitializationStatus>(values.length);
       for (final var item : values) {
          enumByValue.put(item.value, item);
      }
    }

    InitializationStatus(int value) {
        this.value = value;
    }

    public static InitializationStatus fromValue(int value) {
        final var item = enumByValue.getOrDefault(value, null);
        if (item == null)
            throw new IllegalArgumentException(
                    String.format("Invalid InitializationStatus value=%d", value));
        AssertionError.assertTrue(item.value == value,
          "Unexpected InitializationStatus: found=%d expected=%d", item.value, value);
        return item;
    }
}

