//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

public enum InitializationStatus {
    Success((int) 0),
    Unexpected((int) 1),
    OutOfMemory((int) 2),
    AddressInvalid((int) 3),
    AddressLimitExceeded((int) 4),
    SystemResources((int) 5),
    NetworkSubsystem((int) 6);

    public final int value;

    InitializationStatus(int value) {
        this.value = value;
    }

    public static InitializationStatus fromValue(int value) {
        switch (value) {
            case 0: return Success;
            case 1: return Unexpected;
            case 2: return OutOfMemory;
            case 3: return AddressInvalid;
            case 4: return AddressLimitExceeded;
            case 5: return SystemResources;
            case 6: return NetworkSubsystem;
            default: throw new IllegalArgumentException(
                String.format("Invalid InitializationStatus value=%d", value));
        }
    }
}

