//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

public enum PacketStatus {
    Ok((byte) 0),
    TooMuchData((byte) 1),
    ClientShutdown((byte) 2),
    InvalidOperation((byte) 3),
    InvalidDataSize((byte) 4);

    public final byte value;

    PacketStatus(byte value) {
        this.value = value;
    }

    public static PacketStatus fromValue(byte value) {
        var values = PacketStatus.values();
        if (value < 0 || value >= values.length)
            throw new IllegalArgumentException(
                    String.format("Invalid PacketStatus value=%d", value));

        return values[value];
    }
}

