//////////////////////////////////////////////////////////
// This file was auto-generated by java_bindings.zig
// Do not manually modify.
//////////////////////////////////////////////////////////

package com.tigerbeetle;

enum PacketStatus {
    Ok((byte) 0),
    TooMuchData((byte) 1),
    ClientEvicted((byte) 2),
    ClientReleaseTooLow((byte) 3),
    ClientReleaseTooHigh((byte) 4),
    ClientShutdown((byte) 5),
    InvalidOperation((byte) 6),
    InvalidDataSize((byte) 7);

    public final byte value;

    PacketStatus(byte value) {
        this.value = value;
    }

    public static PacketStatus fromValue(byte value) {
        switch (value) {
            case (byte)0: return Ok;
            case (byte)1: return TooMuchData;
            case (byte)2: return ClientEvicted;
            case (byte)3: return ClientReleaseTooLow;
            case (byte)4: return ClientReleaseTooHigh;
            case (byte)5: return ClientShutdown;
            case (byte)6: return InvalidOperation;
            case (byte)7: return InvalidDataSize;
            default: throw new IllegalArgumentException(
                String.format("Invalid PacketStatus value=%d", value));
        }
    }
}

