#!/usr/bin/env node

const messages = [
  'prepare',
  'prepare_ok',
  'commit',
  'request_state_transfer',
  'state_transfer',
  'start_view_change',
  'do_view_change',
  'start_view'
];

const views = [
  'old_view',
  'same_view',
  'new_view'
];

const statuses = [
  'normal',
  'view_change',
  'recovering'
];

const tuples = {};

statuses.forEach(
  function(status) {
    views.forEach(
      function(view) {
        messages.forEach(
          function(message) {
            tuples[`${message}, ${view}, ${status}`] = true;
          }
        );
      }
    );
  }
);

Object.keys(tuples).sort().forEach(
  function(key) {
    console.log(key);
  }
);
