#!/usr/bin/env node
// Extract payload objects from LEV events and write to payloads.json.
var fs = require('fs');
var file = process.argv[2];
if (!file) return console.error('usage: create-payloads <source-events-file>');

var payloads = [];
fs.readFileSync('payloads.txt', 'utf-8').split('\n').forEach(
  function(line) {
    line = line.trim();
    if (!line) return;
    if (!/prepare payload:/.test(line)) return;
    var event = JSON.parse(line);
    var payload = JSON.parse(event.label.split('prepare payload: ').pop());
    payloads.push(payload);
  }
);
fs.writeFileSync('payloads.json', JSON.stringify(payloads), 'utf-8');
console.log(payloads.length + ' payload(s)');
