name: CI
permissions: {}

concurrency:
  group: core-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  merge_group:
  pull_request:
  push:
    branches: ["main"]

env:
  GH_TOKEN: ${{ github.token }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Remove once this is the default (June 2nd, 2026).

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with: { fetch-depth: 2147483647, fetch-tags: true } # Fetch history for "git tag" in build.zig.
      - &cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        # actions/cache (as of v5.0.5) routinely flakes under windows -- it just prints
        # "Cache hit for: Windows-X64-(hash)" and then exits with no other info.
        continue-on-error: ${{ startsWith(runner.os, 'Windows') }}
        with:
          path: ./zig/cache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('./zig/download.sh') }}
      - run: shellcheck ./zig/download.sh
      - shell: pwsh
        run: Invoke-ScriptAnalyzer -Path zig/download.win.ps1 -Severity Error,Warning,Information -EnableExit
      - run: ./zig/download.ps1 && ./zig/zig build ci -- smoke

  test:
    strategy:
      matrix:
        include:
          - { os: 'ubuntu-latest' }
          - { os: 'ubuntu-latest-arm64' }
          # - { os: 'windows-latest' }
          # - { os: 'macos-latest' }
          # - { os: 'macos-15-intel' }
    runs-on: ${{ matrix.os }}
    steps:
      - run: git config --global core.autocrlf false
      - if: matrix.os == 'ubuntu-latest' || matrix.os == 'ubuntu-latest-arm64'
        run: | # Allow unshare for vortex.
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - *checkout
      - *cache
      - run: ./zig/download.ps1 && ./zig/zig build ci -- test

