name: "clients/go: Build"

defaults:
  run:
    working-directory: ./src/clients/go

on:
  # Run CI against any commits pushed to 'main'.
  push:
    branches:
      - 'main'
  # Run CI for any PRs that target 'main' when they are opened or updated.
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - synchronize

jobs:
  shellcheck_scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/shellcheck.sh

  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./tigerbeetle/scripts/install_zig.sh
      - run: ./scripts/rebuild_binaries.sh

      - name: Cache output
        uses: actions/cache@v3
        env:
          cache-name: cache-go-binaries
        with:
          path: src/clients/go/pkg/native
          key: go-binaries-${{ github.sha }}
          restore-keys: |
            go-binaries-${{ github.sha }}

  tests:
    needs: binaries
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache output
        uses: actions/cache@v3
        env:
          cache-name: cache-go-binaries
        with:
          path: src/clients/go/pkg/native
          key: go-binaries-${{ github.sha }}
          restore-keys: |
            go-binaries-${{ github.sha }}
      - run: go test ./...

  # TODO: Windows exit codes broken
  tests_windows:
    needs: binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache output
        uses: actions/cache@v3
        env:
          cache-name: cache-go-binaries
        with:
          path: src/clients/go/pkg/native
          key: go-binaries-${{ github.sha }}
          restore-keys: |
            go-binaries-${{ github.sha }}
      - run: ./zgo.bat test ./...

  build_sample:
    needs: binaries
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache output
        uses: actions/cache@v3
        env:
          cache-name: cache-go-binaries
        with:
          path: src/clients/go/pkg/native
          key: go-binaries-${{ github.sha }}
          restore-keys: |
            go-binaries-${{ github.sha }}
      - run: cd samples/basic && go build

  build_sample_windows:
    needs: binaries
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache output
        uses: actions/cache@v3
        env:
          cache-name: cache-go-binaries
        with:
          path: src/clients/go/pkg/native
          key: go-binaries-${{ github.sha }}
          restore-keys: |
            go-binaries-${{ github.sha }}
      - run: cd samples/basic && ../../zgo.bat build

  upload:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [shellcheck_scripts, binaries, tests, tests_windows, build_sample, build_sample_windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache output
        uses: actions/cache@v3
        env:
          cache-name: cache-go-binaries
        with:
          path: src/clients/go/pkg/native
          key: go-binaries-${{ github.sha }}
          restore-keys: |
            go-binaries-${{ github.sha }}
      - run: mkdir ~/.ssh && echo -e "${{ secrets.TIGERBEETLE_GO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
      - run: git clone --no-checkout git@github.com:tigerbeetledb/tigerbeetle-go.git ~/tigerbeetle-go && cp -R . ~/tigerbeetle-go
      - run: echo -e "# tigerbeetle-go\nThis repo has been automatically generated from [tigerbeetledb/tigerbeetle@${{ github.sha }}](https://github.com/tigerbeetledb/tigerbeetle/commit/${{ github.sha }}). Please see [tigerbeetledb/tigerbeetle](https://github.com/tigerbeetledb/tigerbeetle) for documentation and contributions." > ~/tigerbeetle-go/README.md
      - run: git config --global user.email "bot@tigerbeetle.com" && git config --global user.name "TigerBeetle Bot"
      - run: cd ~/tigerbeetle-go && git add . && git add -f pkg
      - run: cd ~/tigerbeetle-go && git commit -m "Autogenerated commit from tigerbeetledb/tigerbeetle@${{ github.sha }}" && git tag tigerbeetle-${{ github.sha }}
      - run: cd ~/tigerbeetle-go && git push origin main && git push origin tigerbeetle-${{ github.sha }}
