name: Main Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  core:
    uses: ./.github/workflows/pipeline-core.yml
  other:
    uses: ./.github/workflows/pipeline-other.yml

  devhub:
    runs-on: ubuntu-latest
    environment: devhub
    permissions:
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/install_zig.sh
      - run: ./zig/zig build scripts -- devhub --sha=${{ github.sha }}
        env:
          DEVHUBDB_PAT: ${{ secrets.DEVHUBDB_PAT }}
          NYRKIO_TOKEN: ${{ secrets.NYRKIO_TOKEN }}
      - run: git diff --exit-code

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./src/devhub
      - uses: actions/deploy-pages@v1
