name: Release
permissions: {}

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Remove once this is the default (June 2nd, 2026).

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write
      contents: write
      # Required for OIDC.
      # See: https://docs.npmjs.com/trusted-publishers
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2147483647
          fetch-tags: true # Fetch full history for tidy.
          ref: release # Use the 'release' branch even if triggered manually

      - uses: ruby/setup-ruby@97ecb7b512899eb71ab1bf2310a624c6f1589ac6 # v1.308.0
        with:
          ruby-version: '4.0'

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ./zig/cache
          key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('./zig/download.sh') }}
      - run: ./zig/download.sh
      - run: ./zig/zig build scripts -- release --build --publish --language=ruby --sha=${{ github.sha }}
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  alert_failure:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Alert if anything failed
        run: |
          export URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" && \
          curl -d "text=Release process for ${{ github.run_number }} failed! See ${URL} for more information." -d "channel=C04RWHT9EP5" -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" -X POST https://slack.com/api/chat.postMessage
